### ISSUE TITLE
在使用更高分辨率的图片时会报段错误

### ISSUE THREAD

**Issue by asdfczf** [zmsbruce/rm_radar#4]
在使用3072 * 2048分辨率的图片时，运行到对车的推理时报错"段错误"，裁剪至2592 * 2048便可以正常运行。发现robotdetector类对image_size的初始化为1 << 24（16,777,216）,正好略大于2592 * 2048 * 3，但将分辨率提升至3072 * 2048时，便不满足要求，固需要将修改image_size为1 << 25，便可以正常运行。

**Comment by zmsbruce** [comment]
问题在 b4816a33af6187419b4213739a682fb8b94f1d95 中解决，新版本会根据图片的大小给车和装甲板的 `Detector` 分配内存。如果出现了这个 commit 有关的 bug，请在下面进行评论。
