### ISSUE TITLE
对装甲板识别的疑惑

### ISSUE THREAD

**Issue by asdfczf** [zmsbruce/rm_radar#5]
遍历装甲板识别后的容器armor_detections_batch发现，输出的x，y，width，均正常，但height的输出不能明确其含义，甚至有时为负数。若是想实现如识别机器人后框出机器人的操作，该怎样实现？

**Comment by zmsbruce** [comment]
在 Commit b60ca2d1635d891f48f3f2ef4fd30a203c7efa89 中修复
